name: Build and Run C Code

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当 PR 被提交到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # 检出代码

    - name: Set up GCC
      run: |
          sudo apt-get install -y build-essential
          sudo dpkg --add-architecture i386 -y
          sudo apt-get update -y
          sudo apt-get install -y wine64 wine32 wine64-tools

    - name: Compile C code
      run: |
        gcc -o my_program main.c  # 编译 C 程序

    - name: Run the program
      run: |
        ./my_program  # 运行编译后的程序

    - name: Print output
      run: |
        cat my_program.log  # 打印日志（如果有输出）
