name: Generate RootFS

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Target architecture (e.g., amd64, arm64)"
        required: true
        default: "amd64"
      version:
        description: "OS version (e.g., 10.1)"
        required: true
        default: "10.1"
      output:
        description: "RootFS output tarball name"
        required: true
        default: "rootfs.tar.gz"

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (optional, if needed for scripts or dependencies)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install required tools
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap qemu-user-static binfmt-support

      # Step 3: Generate RootFS
      - name: Generate RootFS
        run: |
          mkdir -p rootfs
          sudo debootstrap \
            --arch=${{ inputs.arch }} \
            --components=main,universe,multiverse,restricted \
            ${{ inputs.version }} ./rootfs http://archive.kylinos.cn/kylin/KYLIN-ALL
          sudo tar -czf ${{ inputs.output }} -C ./rootfs .

      # Step 4: Upload RootFS as an artifact
      - name: Upload RootFS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: ${{ inputs.output }}
