name: KylinOS Fcitx-Rime Installation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-fcitx-rime:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Step 3: Pull KylinOS container
      - name: Pull KylinOS image
        run: docker pull kylinsec/kylin:latest

      # Step 4: Run container and install fcitx-rime
      - name: Run KylinOS container
        run: |
          docker run --rm -i --name kylin-fcitx kylinsec/kylin:latest bash -c "
          apt update &&
          apt install -y fcitx fcitx-rime &&
          dpkg --get-selections > /root/installed_packages.txt"

      # Step 5: Save package list
      - name: Copy installed package list
        run: |
          docker create --name kylin-fcitx kylinsec/kylin:latest
          docker cp kylin-fcitx:/root/installed_packages.txt installed_packages.txt
          docker rm kylin-fcitx

      # Step 6: Count the number of installed packages
      - name: Count installed packages
        id: count_packages
        run: |
          if [ -f installed_packages.txt ]; then
            count=$(wc -l < installed_packages.txt)
            echo "installed_count=$count" >> $GITHUB_ENV
          else
            echo "installed_count=0" >> $GITHUB_ENV
          fi


      # Step 8: Upload the package list as an artifact
      - name: Upload package list
        uses: actions/upload-artifact@v4
        with:
          name: installed_packages
          path: installed_packages.txt
