name: Generate Ubuntu 20.04 Rootfs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04  # 运行 Ubuntu 20.04

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install dependencies for debootstrap
      - name: Install debootstrap
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap

      # Step 3: Create the Ubuntu 20.04 root filesystem using debootstrap
      - name: Create Ubuntu 20.04 root filesystem
        run: |
          sudo mkdir /tmp/ubuntu-rootfs
          sudo debootstrap --arch=amd64 focal /tmp/ubuntu-rootfs http://archive.ubuntu.com/ubuntu/

      # Step 4: Compress the generated rootfs into a tarball
      - name: Compress root filesystem
        run: |
          tar -czf /tmp/ubuntu-rootfs.tar.gz -C /tmp ubuntu-rootfs

      # Step 5: Upload the rootfs tarball as an artifact
      - name: Upload rootfs tarball
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-rootfs
          path: /tmp/ubuntu-rootfs.tar.gz

