name: Download and Package Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull existing Docker image
      run: docker pull --platform linux/arm64 marshallasch/ns3:3.33-debug

    - name: Save Docker image as tar
      run: docker save marshallasch/ns3:3.33-debug -o ns3-debug-arm64.tar

    - name: Upload tar to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: arm64-ns3-image
        path: ns3-debug-arm64.tar
