name: Package build-essential and OpenSSL

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and install build-essential and OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential openssl

    - name: Find and copy .deb packages
      run: |
        mkdir -p deb_packages
        dpkg-query -f '${binary:Package}\n' -W build-essential openssl | xargs -I {} dpkg-query -L {} | grep '\.deb$' | xargs -I {} cp {} deb_packages/

    - name: Zip the .deb packages
      run: |
        zip -r essential-packages.zip deb_packages

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: essential-packages
        path: essential-packages.zip
