name: Install MSSQL2019 on Rocky Linux 8 and Download RPMs

on:
  push:
    branches:
      - main

jobs:
  install-mssql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Rocky Linux 8 Docker Image
        run: |
          docker pull rockylinux:8

      - name: Run Rocky Linux 8 Container
        run: |
          docker run --name mssql-rocky -d --privileged -t rockylinux:8 /sbin/init

      - name: Update and Install Dependencies
        run: |
          docker exec mssql-rocky bash -c "
          yum update -y &&
          yum install -y curl wget tar epel-release
          "

      - name: Download Dependencies RPMs
        run: |
          docker exec mssql-rocky bash -c "
          mkdir -p /root/rpms &&
          yum install --downloadonly --downloaddir=/root/rpms curl wget tar epel-release
          "

      - name: Add Microsoft SQL Server Repo
        run: |
          docker exec mssql-rocky bash -c "
          curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo &&
          yum makecache
          "

      - name: Download RPMs for MSSQL Repo
        run: |
          docker exec mssql-rocky bash -c "
          yum install --downloadonly --downloaddir=/root/rpms mssql-server
          "

      - name: Download RPMs for MSSQL Conf Setup
        run: |
          docker exec mssql-rocky bash -c "
          yum install --downloadonly --downloaddir=/root/rpms mssql-tools
          "

      - name: Configure MSSQL Server
        run: |
          docker exec mssql-rocky bash -c "
          /opt/mssql/bin/mssql-conf setup --accept-eula --set-sa-password 'YourPassword123' --set-sa-enabled true
          "

      - name: Download RPMs After MSSQL Configuration
        run: |
          docker exec mssql-rocky bash -c "
          yum install --downloadonly --downloaddir=/root/rpms mssql-server
          "

      - name: Start MSSQL Server
        run: |
          docker exec mssql-rocky bash -c "
          systemctl enable mssql-server &&
          systemctl start mssql-server
          "

      - name: Download RPMs After MSSQL Server Start
        run: |
          docker exec mssql-rocky bash -c "
          yum install --downloadonly --downloaddir=/root/rpms mssql-server
          "

      - name: Verify MSSQL Installation
        run: |
          docker exec mssql-rocky /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123' -Q 'SELECT @@VERSION' 

      - name: Create RPM Tarball
        run: |
          docker exec mssql-rocky bash -c "tar -czf /root/rpms.tar.gz -C /root rpms"

      - name: Upload RPMs Tarball
        uses: actions/upload-artifact@v3
        with:
          name: mssql-rpms
          path: /root/rpms.tar.gz

      - name: Clean Up
        run: |
          docker stop mssql-rocky
          docker rm mssql-rocky
