name: Package build-essential and OpenSSL

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Update package list
      run: sudo apt-get update

    - name: Download build-essential and OpenSSL packages
      run: |
        mkdir -p deb_packages
        apt-get download $(apt-rdepends build-essential openssl | grep -v "^ " | grep -v "^$")
        mv *.deb deb_packages/

    - name: Zip the .deb packages
      run: |
        zip -r essential-packages.zip deb_packages

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: essential-packages
        path: essential-packages.zip

