name: Build and Package OpenSSH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libssl-dev libpam0g-dev libselinux1-dev

    - name: Download OpenSSH source
      run: |
        wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz
        tar -xzf openssh-9.8p1.tar.gz
        cd openssh-9.8p1

    - name: Configure and compile OpenSSH
      run: |
        cd openssh-9.8p1
        ./configure --prefix=/usr --sysconfdir=/etc/ssh --with-pam --with-selinux
        make

    - name: Package OpenSSH
      run: |
        tar -czf openssh-9.8p1-compiled.tar.gz openssh-9.8p1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openssh-9.8p1-compiled
        path: openssh-9.8p1-compiled.tar.gz
