name: Install MSSQL2019 on Rocky Linux 8 and Cache RPMs

on:
  push:
    branches:
      - main

jobs:
  install-mssql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Rocky Linux 8 Docker Image
        run: |
          docker pull rockylinux:8

      - name: Run Rocky Linux 8 Container
        run: |
          docker run --name mssql-rocky -d --privileged -t rockylinux:8 /sbin/init

      - name: Set Custom yum Cache Directory
        run: |
          mkdir -p /tmp/yum-rpm

      - name: Update and Install Dependencies
        run: |
          docker exec mssql-rocky bash -c "
          yum update -y &&
          yum install --downloadonly --downloaddir=/tmp/yum-rpm curl wget tar epel-release
          yum install -y curl wget tar epel-release
          "
      - name: Add Microsoft SQL Server Repo
        run: |
          docker exec mssql-rocky bash -c "
          curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo &&
          yum makecache
          "
          
      - name: Install MSSQL Server
        run: |
          docker exec mssql-rocky bash -c "
          yum install --downloadonly --downloaddir=/tmp/yum-rpm mssql-server
          "

      - name: Create RPM Cache Tarball
        run: |
          docker exec mssql-rocky bash -c "ls -l /tmp/yum-rpm"

      - name: Upload RPM Cache Tarball
        uses: actions/upload-artifact@v4
        with:
          name: mssql-yum-cache
          path: /tmp/yum-rpm

      - name: Clean Up
        run: |
          docker stop mssql-rocky
          docker rm mssql-rocky
