name: Query Docker Image Metadata

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  query-metadata:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新的运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出仓库代码（如果需要用到仓库中的某些内容）

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # 设置 Docker 构建环境

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/ggerganov/llama.cpp:server-cuda--b1-2a63caa  # 拉取 Docker 镜像

      - name: Inspect Docker image metadata
        run: |
          docker inspect ghcr.io/ggerganov/llama.cpp:server-cuda--b1-2a63caa  # 查询并输出镜像元数据
        id: inspect_output

      - name: Output image metadata
        run: |
          echo "Docker Image Metadata:"
          echo "${{ steps.inspect_output.outputs }}"
