name: Download Docker Image as Offline Package

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-save-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull ARM64 Docker Image
        run: |
          docker pull --platform linux/arm64 hagb/docker-easyconnect:7.6.7

      - name: Save Docker Image as tar
        run: |
          docker save --output=hagb-docker-easyconnect-7.6.7-arm64.tar hagb/docker-easyconnect:7.6.7

      - name: Upload Docker Image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hagb-docker-easyconnect-7.6.7-arm64
          path: hagb-docker-easyconnect-7.6.7-arm64.tar
