name: Build and Install OpenSSL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential checkinstall zlib1g-dev

    - name: Download OpenSSL
      run: |
        wget https://www.openssl.org/source/openssl-3.0.13.tar.gz
        tar -xzvf openssl-3.0.13.tar.gz
        

    - name: Configure and build OpenSSL
      run: |
        cd openssl-3.0.13
        ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
        make

    - name: Package OpenSSL
      run: |
        tar -czf openssl-3.0.13-compiled.tar.gz openssl-3.0.13
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openssl-3.0.13-compiled
        path: openssl-3.0.13-compiled.tar.gz
