name: Download and Package Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Pull existing Docker image
      run: docker pull --platform linux/amd64 nginx/nginx:latest
    - name: Save Docker image as tar
      run: docker save nginx/nginx:latest -o nginx.tar

    - name: Upload tar to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: arm64-ns3-image
        path: nginx.tar


