name: Build OpenSSH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential fakeroot dpkg-dev

    - name: Download OpenSSH source
      run: wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz

    - name: Extract source
      run: tar -xzf openssh-9.8p1.tar.gz

    - name: Build OpenSSH
      run: |
        cd openssh-9.8p1
        ./configure
        make

    - name: Create deb package
      run: |
        cd openssh-9.8p1
        sudo checkinstall --pkgname=openssh --pkgversion=9.8p1 --backup=no --deldoc=yes --fstrans=no --default

    - name: Upload deb package
      uses: actions/upload-artifact@v4
      with:
        name: openssh-9.8p1.deb
        path: openssh-9.8p1/openssh_9.8p1-1_amd64.deb
