name: Build Chromium ARM64 AppImage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置工作环境
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo apt-get install -y libfuse2 build-essential wget

      # 拉取并运行 Debian 容器，准备打包环境
      - name: Set up Debian container
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --name debian-arm64 -dit --platform linux/arm64 debian:bullseye
          docker exec -it debian-arm64 apt-get update
          docker exec -it debian-arm64 apt-get install -y wget libfuse2 build-essential zsync

      # 下载 Chromium 的 ARM64 DEB 包
      - name: Download Chromium deb package
        run: |
          docker exec -it debian-arm64 bash -c "
            mkdir -p /workspace && cd /workspace
            wget http://ftp.debian.org/debian/pool/main/c/chromium/chromium_*.deb
          "

      # 提取 deb 包并设置 AppDir 结构
      - name: Extract deb package and set up AppDir
        run: |
          docker exec -it debian-arm64 bash -c "
            apt-get install -y dpkg
            cd /workspace
            dpkg-deb -x chromium_*.deb AppDir
            dpkg-deb -e chromium_*.deb AppDir/DEBIAN
          "

      # 下载 AppImage 工具并生成 AppImage
      - name: Build AppImage
        run: |
          docker exec -it debian-arm64 bash -c "
            cd /workspace
            wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-arm64.AppImage
            chmod +x appimagetool-arm64.AppImage
            ./appimagetool-arm64.AppImage AppDir
          "

      # 将生成的 AppImage 上传为 Artifact
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: chromium-arm64.AppImage
          path: /workspace/chromium-arm64.AppImage
