name: Download and Package Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull existing Docker image
      run: docker pull marshallasch/ns3:3.33-optimized

    - name: Create ARM64 Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t arm64-ns3-image --load .

    - name: Save Docker image as tar
      run: docker save arm64-ns3-image -o arm64-ns3-image.tar

    - name: Upload tar to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: arm64-ns3-image
        path: arm64-ns3-image.tar
